<?php
declare(strict_types=1);

function influencer_requirement_payload(array $input, ?array $current = null): array
{
    $label = safe_trim($input['label'] ?? $current['label'] ?? '');
    $type = safe_trim($input['field_type'] ?? $current['field_type'] ?? 'file');
    if ($label === '') throw new AppError(422, 'Field label is required');
    if (!in_array($type, ['text', 'number', 'file'], true)) throw new AppError(422, 'Invalid field type');
    return ['label'=>$label, 'field_type'=>$type, 'accepted_file_types'=>$type === 'file' ? safe_trim($input['accepted_file_types'] ?? $current['accepted_file_types'] ?? 'pdf,jpg,png') : '', 'max_file_size_mb'=>max(1, min(100, (int)($input['max_file_size_mb'] ?? $current['max_file_size_mb'] ?? 10))), 'is_required'=>cms_bool($input['is_required'] ?? $current['is_required'] ?? true, true), 'sort_order'=>(int)($input['sort_order'] ?? $current['sort_order'] ?? 0), 'updated_at'=>now_db()];
}
function influencer_or_fail(PDO $db, string $id): array { $item=fetch_one($db,'SELECT id FROM influencers WHERE id=:id LIMIT 1',[':id'=>$id]); if(!$item) throw new AppError(404,'Influencer not found'); return $item; }
function handle_admin_influencer_requirements(PDO $db, string $influencerId): void { require_admin($db); influencer_or_fail($db,$influencerId); json_response(['requirements'=>influencer_requirement_rows($db,$influencerId)]); }
function shared_influencer_requirements(PDO $db): array { $source=fetch_one($db, 'SELECT influencer_id FROM influencer_requirements ORDER BY created_at ASC, id ASC LIMIT 1'); return $source ? fetch_all($db, 'SELECT * FROM influencer_requirements WHERE influencer_id=:id ORDER BY sort_order ASC, created_at ASC', [':id'=>$source['influencer_id']]) : []; }
function copy_shared_influencer_requirements(PDO $db, string $influencerId): void { foreach(shared_influencer_requirements($db) as $field) { insert_row($db, 'influencer_requirements', ['id'=>uuid_v4(), 'influencer_id'=>$influencerId, 'label'=>$field['label'], 'field_type'=>$field['field_type'], 'accepted_file_types'=>$field['accepted_file_types'], 'max_file_size_mb'=>$field['max_file_size_mb'], 'is_required'=>$field['is_required'], 'sort_order'=>$field['sort_order'], 'created_at'=>now_db(), 'updated_at'=>now_db()]); } }
function handle_admin_influencer_requirement_create(PDO $db, string $influencerId): void { require_admin($db); influencer_or_fail($db,$influencerId); $field=influencer_requirement_payload(request_data()); $now=now_db(); $influencers=fetch_all($db,'SELECT id FROM influencers ORDER BY created_at ASC'); $db->beginTransaction(); try { foreach($influencers as $influencer) insert_row($db,'influencer_requirements',['id'=>uuid_v4(),'influencer_id'=>$influencer['id'],...$field,'created_at'=>$now]); $db->commit(); } catch(Throwable $error) { if($db->inTransaction()) $db->rollBack(); throw $error; } $requirements=influencer_requirement_rows($db,$influencerId); $requirement=end($requirements) ?: null; json_response(['message'=>'Customer field added for every influencer','requirement'=>$requirement],201); }
function handle_admin_influencer_requirement_delete(PDO $db, string $id): void { require_admin($db); $field=fetch_one($db,'SELECT * FROM influencer_requirements WHERE id=:id LIMIT 1',[':id'=>$id]); if(!$field) throw new AppError(404,'Customer field not found'); execute_statement($db,'DELETE FROM influencer_requirements WHERE label=:label AND field_type=:field_type AND accepted_file_types=:accepted_file_types AND max_file_size_mb=:max_file_size_mb AND is_required=:is_required AND sort_order=:sort_order',[':label'=>$field['label'],':field_type'=>$field['field_type'],':accepted_file_types'=>$field['accepted_file_types'],':max_file_size_mb'=>$field['max_file_size_mb'],':is_required'=>$field['is_required'],':sort_order'=>$field['sort_order']]); json_response(['message'=>'Customer field removed for every influencer']); }
function influencer_requirement_rows(PDO $db, string $influencerId): array { $rows=fetch_all($db,'SELECT * FROM influencer_requirements WHERE influencer_id=:id ORDER BY sort_order ASC,created_at ASC',[':id'=>$influencerId]); foreach($rows as &$row){$row['is_required']=(bool)$row['is_required'];$row['max_file_size_mb']=(int)$row['max_file_size_mb'];} return $rows; }
function handle_admin_influencer_booking_summary(PDO $db): void { require_admin($db); $rows=fetch_all($db,"SELECT influencer_id, COUNT(*) AS total_bookings, SUM(status = 'pending') AS pending_approval FROM services WHERE influencer_id IS NOT NULL GROUP BY influencer_id"); $summary=[]; foreach($rows as $row) $summary[$row['influencer_id']]=['total_bookings'=>(int)$row['total_bookings'],'pending_approval'=>(int)$row['pending_approval']]; json_response(['summary'=>$summary]); }
function handle_admin_influencer_bookings(PDO $db, string $influencerId): void { require_admin($db); influencer_or_fail($db,$influencerId); $bookings=fetch_all($db,"SELECT s.id,s.status,s.price,s.notes,s.admin_remarks,s.created_at,u.name AS customer_name,u.email AS customer_email,u.phone AS customer_phone,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.service_id=s.id AND (p.status='paid' OR p.verification_status='verified')),0) AS amount_received FROM services s JOIN users u ON u.id=s.user_id WHERE s.influencer_id=:id ORDER BY s.created_at DESC",[':id'=>$influencerId]); foreach($bookings as &$booking){$booking['price']=(float)$booking['price'];$booking['amount_received']=(float)$booking['amount_received'];$values=fetch_all($db,'SELECT r.label,r.field_type,v.value_text,d.original_name,d.file_url,d.mime_type FROM influencer_requirement_values v JOIN influencer_requirements r ON r.id=v.influencer_requirement_id LEFT JOIN documents d ON d.id=v.document_id WHERE v.service_id=:id ORDER BY r.sort_order ASC,r.label ASC',[':id'=>$booking['id']]); $booking['submitted_fields']=$values;} json_response(['bookings'=>$bookings]); }
function handle_admin_influencer_booking_review(PDO $db, string $serviceId): void { require_admin($db); $input=request_data(); $status=safe_trim($input['status'] ?? ''); if(!in_array($status,['approved','rejected'],true)) throw new AppError(422,'Choose approved or rejected'); $service=fetch_one($db,'SELECT * FROM services WHERE id=:id AND influencer_id IS NOT NULL LIMIT 1',[':id'=>$serviceId]); if(!$service) throw new AppError(404,'Influencer booking not found'); if($service['status']!=='pending') throw new AppError(422,'Only pending bookings can be reviewed'); $reason=safe_trim($input['reason'] ?? ''); if($status==='rejected' && $reason==='') throw new AppError(422,'A denial reason is required'); $remarks=$status==='approved' ? 'Booking approved. Payment is now available.' : $reason; $db->beginTransaction(); try { update_row($db,'services',['status'=>$status,'admin_remarks'=>$remarks,'updated_at'=>now_db()],'id=:id',[':id'=>$serviceId]); if($status==='approved') { $now=now_db(); execute_statement($db,"UPDATE documents d JOIN influencer_requirement_values v ON v.document_id=d.id SET d.status='approved',d.remarks='Approved with influencer booking',d.reviewed_at=:reviewedAt,d.updated_at=:updatedAt WHERE v.service_id=:id",[':reviewedAt'=>$now,':updatedAt'=>$now,':id'=>$serviceId]); } $db->commit(); } catch(Throwable $error) { if($db->inTransaction()) $db->rollBack(); throw $error; } create_notification($db,['userId'=>$service['user_id'],'title'=>$status==='approved'?'Influencer booking approved':'Influencer booking declined','message'=>$status==='approved' ? $service['type'].' has been approved. You can now make payment.' : $service['type'].' was declined. Reason: '.$reason,'category'=>$status==='approved'?'payment':'service','link'=>$status==='approved'?'/dashboard/payments':'/dashboard/services','actionLabel'=>$status==='approved'?'Pay now':'View booking']); json_response(['message'=>$status==='approved'?'Booking approved. The customer can now pay.':'Booking declined and the customer has been notified.']); }
function handle_public_influencer_requirements(PDO $db, string $id): void { $influencer=fetch_one($db,'SELECT id,name,is_active FROM influencers WHERE id=:id LIMIT 1',[':id'=>$id]); if(!$influencer || !(bool)$influencer['is_active']) throw new AppError(404,'Influencer not available'); json_response(['influencer'=>$influencer,'requirements'=>influencer_requirement_rows($db,$id)]); }
function handle_create_influencer_booking(PDO $db, string $influencerId): void {
    $user=current_user($db); $influencer=fetch_one($db,'SELECT * FROM influencers WHERE id=:id LIMIT 1',[':id'=>$influencerId]); if(!$influencer || !(bool)$influencer['is_active']) throw new AppError(422,'This influencer is not available');
    $input=request_data(); $requirements=influencer_requirement_rows($db,$influencerId);
    foreach($requirements as $requirement){ $key='field_'.$requirement['id']; $file=request_file($key); $value=$input[$key]??null; if($requirement['is_required'] && (($requirement['field_type']==='file' && $file===null) || ($requirement['field_type']!=='file' && trim((string)$value)===''))) throw new AppError(422,$requirement['label'].' is required'); if($file && (int)($file['size']??0) > $requirement['max_file_size_mb']*1024*1024) throw new AppError(422,$requirement['label'].' exceeds the maximum file size'); }
    $serviceId=uuid_v4(); insert_row($db,'services',['id'=>$serviceId,'user_id'=>$user['id'],'requested_by_client'=>1,'catalog_service_id'=>null,'influencer_id'=>$influencerId,'type'=>'Influencer Booking — '.$influencer['name'],'description'=>$influencer['bio'] ?? '','price'=>$influencer['booking_price'],'status'=>'pending','priority'=>'medium','notes'=>safe_trim($input['notes']??''),'admin_remarks'=>'','completed_at'=>null,'created_at'=>now_db(),'updated_at'=>now_db()]);
    foreach($requirements as $requirement){ $key='field_'.$requirement['id']; $file=request_file($key); $value=$input[$key]??null; $documentId=null; if($file){ $allowed=array_filter(array_map('trim',explode(',',(string)$requirement['accepted_file_types']))); $extension=strtolower(pathinfo((string)($file['name']??''),PATHINFO_EXTENSION)); if($allowed!==[] && !in_array($extension,$allowed,true)) throw new AppError(422,$requirement['label'].' has an unsupported file type'); $stored=store_uploaded_file($file,build_user_storage_relative_dir((string)$user['id'],$influencer['name']),['pdf','png','jpg','jpeg'],['application/pdf','image/png','image/jpeg']); $documentId=uuid_v4(); insert_row($db,'documents',['id'=>$documentId,'user_id'=>$user['id'],'uploaded_by_id'=>$user['id'],'title'=>$requirement['label'],'document_type'=>$requirement['label'],'service_type'=>'Influencer Booking — '.$influencer['name'],'input_type'=>'file','text_value'=>'','filename'=>$stored['filename'],'original_name'=>$stored['originalName'],'relative_path'=>$stored['relativePath'],'storage_folder'=>$stored['storageFolder'],'file_url'=>$stored['fileUrl'],'mime_type'=>$stored['mimeType'],'status'=>'pending','remarks'=>'','notes'=>'','reviewed_by_id'=>null,'reviewed_at'=>null,'created_at'=>now_db(),'updated_at'=>now_db()]); } if(($value===null||$value==='') && $documentId===null) continue; insert_row($db,'influencer_requirement_values',['id'=>uuid_v4(),'service_id'=>$serviceId,'influencer_requirement_id'=>$requirement['id'],'value_text'=>$value===null?'':(string)$value,'document_id'=>$documentId,'created_at'=>now_db()]); }
    json_response(['message'=>'Influencer booking submitted','serviceId'=>$serviceId],201);
}
