import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api, { extractApiError } from '../../lib/api.js'
import Loader from '../../components/common/Loader.jsx'
import PageHeader from '../../components/common/PageHeader.jsx'
import { Icon } from '../public/Home.jsx'

const serviceMeta = { 'tax-service': { icon: 'calculator', tone: 'blue', path: '/services' }, marketing: { icon: 'megaphone', tone: 'rose', path: '/marketing' }, influencers: { icon: 'users', tone: 'violet', path: '/influencers' }, 'web-apps': { icon: 'code', tone: 'orange', path: '/web-apps' } }
const countDescendants = (node) => (node.children || []).reduce((count, child) => count + 1 + countDescendants(child), 0)

export default function PublicServicesManager() {
  const navigate = useNavigate(); const [services, setServices] = useState([]); const [loading, setLoading] = useState(true); const [savingId, setSavingId] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { api.get('/api/admin/service-tree').then(({ data }) => setServices(data.services || [])).catch((error) => setMessage(extractApiError(error))).finally(() => setLoading(false)) }, [])
  const totals = useMemo(() => ({ active: services.filter((service) => service.is_active).length, inactive: services.filter((service) => !service.is_active).length, children: services.reduce((total, service) => total + countDescendants(service), 0) }), [services])
  const updateAvailability = async (service) => { const nextActive = !service.is_active; setSavingId(service.id); setMessage(''); try { await api.patch(`/api/admin/service-nodes/${service.id}`, { is_active: nextActive }); setServices((current) => current.map((item) => item.id === service.id ? { ...item, is_active: nextActive } : item)); setMessage(nextActive ? `${service.name} is live. Its child services can be requested again.` : `${service.name} is now coming soon. Opening any child service will show the Coming Soon page.`) } catch (error) { setMessage(extractApiError(error)) } finally { setSavingId('') } }
  if (loading) return <Loader message="Loading main service controls..." />
  return <div className="page-stack public-services-admin-page"><PageHeader eyebrow="Public website" title="Main Service Control" description="Turn each main service on or off. When a service is off, every child service leads visitors to a Coming Soon page." />{message ? <p className="form-message">{message}</p> : null}<section className="main-service-overview"><article><span>Live now</span><strong>{totals.active}</strong><small>Main services available to visitors</small></article><article><span>Coming soon</span><strong>{totals.inactive}</strong><small>Main services currently paused</small></article><article><span>Child services</span><strong>{totals.children}</strong><small>Offerings protected by these controls</small></article></section><section className="main-service-control-panel"><header className="main-service-control-head"><div><span className="admin-surface-eyebrow">Availability controls</span><h3>Choose what visitors can access</h3><p>Switching a main service off never deletes its setup. Switch it back on to make all child services available again.</p></div></header><div className="main-service-control-grid">{services.map((service) => { const meta = serviceMeta[service.slug] || { icon: 'briefcase', tone: 'blue', path: '/services' }; const childCount = countDescendants(service); const busy = savingId === service.id; return <article className={`main-service-control-card tone-${meta.tone}${service.is_active ? ' is-live' : ' is-paused'}`} key={service.id}><div className="main-service-card-top"><span className="main-service-icon"><Icon name={meta.icon} /></span><span className={`main-service-state ${service.is_active ? 'live' : 'paused'}`}><i />{service.is_active ? 'Live' : 'Coming soon'}</span></div><div><h3>{service.name}</h3><p>{service.description || `${childCount} child service${childCount === 1 ? '' : 's'} connected to this main service.`}</p></div><div className="main-service-card-meta"><span>{childCount} child service{childCount === 1 ? '' : 's'}</span><a href={meta.path} rel="noreferrer" target="_blank">Preview website ↗</a></div><footer><label className="main-service-switch"><input aria-label={`Set ${service.name} ${service.is_active ? 'inactive' : 'active'}`} checked={service.is_active} disabled={busy} onChange={() => updateAvailability(service)} type="checkbox" /><span /><b>{busy ? 'Saving…' : service.is_active ? 'Service active' : 'Service inactive'}</b></label><button className="button button-ghost button-compact" onClick={() => navigate(`/admin/services/${service.slug}`)} type="button">Manage children</button></footer></article> })}</div></section></div>
}
