import { useEffect, useState } from 'react'
import api, { extractApiError } from '../../lib/api.js'
import Loader from '../../components/common/Loader.jsx'
import PageHeader from '../../components/common/PageHeader.jsx'
import { Link, useLocation } from 'react-router-dom'
import ContentManager from './ContentManager.jsx'

const keys = [['company_name','Company name'],['phone','Phone'],['whatsapp','WhatsApp number'],['email','Email'],['address','Address'],['instagram','Instagram URL'],['facebook','Facebook URL'],['youtube','YouTube URL'],['footer_content','Footer content'],['copyright','Copyright'],['seo_title','Default SEO title'],['seo_description','Default SEO description'],['meta_pixel_id','Meta Pixel ID'],['hero_title','Homepage hero title'],['hero_description','Homepage hero description'],['hero_cta_text','Hero CTA text']]
export default function WebsiteSettings() { const location=useLocation(); const isFaqPage=location.pathname.endsWith('/faqs'); const [settings,setSettings]=useState({}); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); useEffect(()=>{if(isFaqPage)return;api.get('/api/admin/settings').then(({data})=>setSettings(data.settings||{})).catch((e)=>setMessage(extractApiError(e))).finally(()=>setLoading(false))},[isFaqPage]); const save=async(e)=>{e.preventDefault(); try{await api.put('/api/admin/settings',settings);setMessage('Settings saved successfully.')}catch(error){setMessage(extractApiError(error))}}; const tabs=<nav className="admin-settings-tabs"><Link className={!isFaqPage?'active':''} to="/admin/settings">General settings</Link><Link className={isFaqPage?'active':''} to="/admin/settings/faqs">FAQs</Link></nav>; if(isFaqPage)return <div className="page-stack"><PageHeader eyebrow="Website configuration" title="Website Settings" description="Control global site configuration and public FAQ content."/>{tabs}<ContentManager resource="faqs"/></div>; if(loading)return <Loader message="Loading website settings..."/>; return <div className="page-stack"><PageHeader eyebrow="Website configuration" title="Website Settings" description="These values are used by the public site and its SEO metadata."/>{tabs}{message&&<p className="form-message">{message}</p>}<form className="panel admin-inline-editor admin-inline-editor-wrap" onSubmit={save}>{keys.map(([key,label])=><label key={key}>{label}{key.includes('description')||key==='address'||key==='footer_content'?<textarea rows="3" value={settings[key]||''} onChange={(e)=>setSettings({...settings,[key]:e.target.value})}/>:<input value={settings[key]||''} onChange={(e)=>setSettings({...settings,[key]:e.target.value})}/>}</label>)}<button className="button button-primary" type="submit">Save settings</button></form></div> }
